import Head from 'next/head';
import styles from '../styles/Home.module.css';
import GifSearch from '../components/gifSearch';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Giphy Explorer - The Best Gif Search Page Ever</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-3xl mb-10 capitalize">
          Find the coolest gifs on the internet.
        </h1>
        <GifSearch />
      </main>
    </div>
  )
}
